/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /wg/stor2a/isucan/repos/wg_debs/octomap_msgs-release/srv/GetOctomap.srv
 *
 */


#ifndef OCTOMAP_MSGS_MESSAGE_GETOCTOMAP_H
#define OCTOMAP_MSGS_MESSAGE_GETOCTOMAP_H

#include <ros/service_traits.h>


#include <octomap_msgs/GetOctomapRequest.h>
#include <octomap_msgs/GetOctomapResponse.h>


namespace octomap_msgs
{

struct GetOctomap
{

typedef GetOctomapRequest Request;
typedef GetOctomapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetOctomap
} // namespace octomap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::octomap_msgs::GetOctomap > {
  static const char* value()
  {
    return "c74335a6bc30ba3766f4f6bcc2364be3";
  }

  static const char* value(const ::octomap_msgs::GetOctomap&) { return value(); }
};

template<>
struct DataType< ::octomap_msgs::GetOctomap > {
  static const char* value()
  {
    return "octomap_msgs/GetOctomap";
  }

  static const char* value(const ::octomap_msgs::GetOctomap&) { return value(); }
};


// service_traits::MD5Sum< ::octomap_msgs::GetOctomapRequest> should match 
// service_traits::MD5Sum< ::octomap_msgs::GetOctomap > 
template<>
struct MD5Sum< ::octomap_msgs::GetOctomapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::octomap_msgs::GetOctomap >::value();
  }
  static const char* value(const ::octomap_msgs::GetOctomapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::octomap_msgs::GetOctomapRequest> should match 
// service_traits::DataType< ::octomap_msgs::GetOctomap > 
template<>
struct DataType< ::octomap_msgs::GetOctomapRequest>
{
  static const char* value()
  {
    return DataType< ::octomap_msgs::GetOctomap >::value();
  }
  static const char* value(const ::octomap_msgs::GetOctomapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::octomap_msgs::GetOctomapResponse> should match 
// service_traits::MD5Sum< ::octomap_msgs::GetOctomap > 
template<>
struct MD5Sum< ::octomap_msgs::GetOctomapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::octomap_msgs::GetOctomap >::value();
  }
  static const char* value(const ::octomap_msgs::GetOctomapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::octomap_msgs::GetOctomapResponse> should match 
// service_traits::DataType< ::octomap_msgs::GetOctomap > 
template<>
struct DataType< ::octomap_msgs::GetOctomapResponse>
{
  static const char* value()
  {
    return DataType< ::octomap_msgs::GetOctomap >::value();
  }
  static const char* value(const ::octomap_msgs::GetOctomapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OCTOMAP_MSGS_MESSAGE_GETOCTOMAP_H
