(cl:defpackage octomap_msgs-srv
  (:use )
  (:export
   "GETOCTOMAP"
   "<GETOCTOMAP-REQUEST>"
   "GETOCTOMAP-REQUEST"
   "<GETOCTOMAP-RESPONSE>"
   "GETOCTOMAP-RESPONSE"
   "BOUNDINGBOXQUERY"
   "<BOUNDINGBOXQUERY-REQUEST>"
   "BOUNDINGBOXQUERY-REQUEST"
   "<BOUNDINGBOXQUERY-RESPONSE>"
   "BOUNDINGBOXQUERY-RESPONSE"
  ))

